// GENERATED by scripts/gen-icons.mjs -- do not edit. Re-run the script.
//
// The versioned URLs of the opaque app icons, rasterized from
// public/brand/Axia Atlas_Vector Logo_Accent Color_1024x1024.png.
// The version is a hash of that file, so a new mark gets new URLs and no
// installed device or service-worker cache can keep serving the old one.
export const APP_ICONS = {
  "version": "2bf1a029",
  "icon48": "/icon-48.2bf1a029.png",
  "icon96": "/icon-96.2bf1a029.png",
  "icon192": "/icon-192.2bf1a029.png",
  "icon512": "/icon-512.2bf1a029.png",
  "icon512Maskable": "/icon-512-maskable.2bf1a029.png",
  "apple": "/apple-icon.2bf1a029.png"
} as const
