import type { MetadataRoute } from 'next'

/* Web app manifest. Icons are the same opaque Deep-Spruce squares linked from
   app/layout.tsx, generated by scripts/gen-icons.mjs from the portal's
   canonical mark — one source, one mark, everywhere.

   They are full-bleed with no rounding and no alpha, which is exactly what
   `maskable` wants: Android applies its own mask and crops to roughly the
   middle 80%, and the generator frames the mark at 39% of the canvas — the
   brand asset's own framing — so it sits far inside that crop. 512 is here for
   the PWA install prompt only; the icons Google reads are /favicon.ico and the
   PNGs declared in app/layout.tsx.

   There is deliberately no SVG entry HERE. The site does ship an adaptive
   src/app/icon.svg for the browser tab, but a PWA icon is composited against
   backgrounds the manifest does not control, so this list stays opaque. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Axia Atlas',
    short_name: 'Axia Atlas',
    description: 'Marketing that makes you impossible to miss.',
    start_url: '/',
    display: 'standalone',
    // The site's ground, not the brand green: these paint the PWA splash and
    // the Android browser chrome, and a spruce bar above a #070C09 page reads
    // as a rendering bug rather than as branding.
    background_color: '#070C09',
    theme_color: '#070C09',
    icons: [
      { src: '/icon-48.png', sizes: '48x48', type: 'image/png', purpose: 'any' },
      { src: '/icon-96.png', sizes: '96x96', type: 'image/png', purpose: 'any' },
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
